export const ALL_PROJECTALL_REQUEST ="ALL_PROJECTALL_REQUEST";
export const ALL_PROJECTALL_SUCCESS ="ALL_PROJECTALL_SUCCESS";
export const ALL_PROJECTALL_FAIL ="ALL_PROJECTALL_FAIL";

export const PROJECT_DETAILS_REQUEST ="PROJECT_DETAILS_REQUEST";
export const PROJECT_DETAILS_SUCCESS ="PROJECT_DETAILS_SUCCESS";
export const PROJECT_DETAILS_FAIL ="PROJECT_DETAILS_FAIL";
export const CLEAR_ERRORS ="CLEAR_ERRORS";